"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"   Francis Vidal <francis.vidal@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  call plug#begin('~/.vim/plugged')
  let g:_plugins=['general', 'git', 'programming', 'completion', 'python']
  let g:neocomplcache_enable_at_startup = 1
  source ~/.vim/plugins.vim
  " Add extra bundles here...
  " Bundle 'reponame'
  call plug#end()
endif

" For base16-vim
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" Powerline setup
set laststatus=2
set term=xterm-256color
set termencoding=utf-8
let g:airline_powerline_fonts = 1
